BASE_DIRECTORY = "/Users/fredriko/Dropbox/data/wordspaces/"
RAW_DATA_DIRECTORY = BASE_DIRECTORY + "text/raw-text"
PHRASE_DATA_DIRECTORY = BASE_DIRECTORY + "text/phrase-text/"
MODELS_DIRECTORY = BASE_DIRECTORY + "models/"
PHRASE_MODELS_DIRECTORY = MODELS_DIRECTORY + "phrase-models/"
WEBHOSE_ZIP_DIRECTORY = BASE_DIRECTORY + "zip/webhose-unzipped/"